#!/bin/bash

big_info() {
  printf "\e[34m
================================================
$1
================================================\n\e[m"
}

BRANCH=$1

# branch 指定がなければ current branch を指定したとみなす
if [ -z "$BRANCH" ]; then
  BRANCH=`git rev-parse --abbrev-ref HEAD`
fi

SSH_OPTION="isu-kayac"

big_info "deploy $BRANCH to $SSH_OPTION"
ssh $SSH_OPTION "sudo -u isucon /home/isucon/deploy_on_remote $BRANCH"
